#
# Copyright (C) 2016 Urchinly <wabisabi@urchinly.uk>
#

version: "2"

services:
  ingest:
    image: urchinly/wabi-ingest
    environment:
     - WABI_SHARE=/data/vault
     - SPRING_PROFILES_ACTIVE=prod
     - SPRING_DATA_MONGODB_URI=mongodb://wabi_mongo_1/wabi
     - SPRING_RABBITMQ_ADDRESSES=wabi_rabbitmq_1,wabi_rabbitmq_2,wabi_rabbitmq_3
    ports:
     - "9081:8081"
    volumes:
     - /tmp
     - shared-volume:/data/vault
    depends_on:
     - rabbitmq
     - mongo
    networks:
     - sabi-tier
     - wabi-tier

  expose:
    image: urchinly/wabi-expose
    environment:
     - WABI_SHARE=/data/vault
     - SPRING_PROFILES_ACTIVE=prod
     - SPRING_DATA_MONGODB_URI=mongodb://wabi_mongo_1/wabi
     - SPRING_RABBITMQ_ADDRESSES=wabi_rabbitmq_1,wabi_rabbitmq_2,wabi_rabbitmq_3
    ports:
      - "9082:8082"
    volumes_from:
     - ingest:rw
    depends_on:
     - rabbitmq
     - mongo
    networks:
     - sabi-tier
     - wabi-tier

  search:
    image: urchinly/wabi-search
    environment:
     - SPRING_PROFILES_ACTIVE=prod
     - SPRING_RABBITMQ_ADDRESSES=wabi_rabbitmq_1,wabi_rabbitmq_2,wabi_rabbitmq_3
     - SPRING_DATA_SOLR_HOST=http://wabi_elasticsearch_1
    ports:
     - "9088:8088"
    volumes:
     - /tmp
    depends_on:
     - rabbitmq
     - elasticsearch
    networks:
     - sabi-tier
     - wabi-tier

  rabbitmq:
    image: urchinly/wabi-rabbitmq
    environment:
# broken - RABBITMQ_NODENAME=wabi
     - RABBITMQ_ERLANG_COOKIE=wabi
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
     - RABBITMQ_DEFAULT_VHOST=/
    ports:
     - "5672:5672"
     - "15672:15672"
    volumes:
     - rabbitmq-volume:/var/lib/rabbitmq/mnesia/wabi
    networks:
     - wabi-tier
    labels:
     - "uk.urchinly.tech=data"

  elasticsearch:
    image: elasticsearch:1.5.2
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
     - elasticsearch-volume:/usr/share/elasticsearch/data
    networks:
     - wabi-tier
    labels:
     - "uk.urchinly.tech=data"

  mongo:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - mongo-volume:/data/db
    networks:
     - wabi-tier
    labels:
     - "uk.urchinly.tech=data"

volumes:
  shared-volume:
    driver: local
  rabbitmq-volume:
    driver: local
  mongo-volume:
    driver: local
  elasticsearch-volume:
    driver: local

networks:
  sabi-tier:
    driver: bridge
  wabi-tier:
    driver: bridge
