#
# Copyright (C) ${year} Urchinly <wabi@urchinly.uk>
#

FROM elasticsearch
MAINTAINER docker@urchinly.uk
LABEL uk.urchinly.tech=data
EXPOSE 9200
EXPOSE 9300
ADD config/elasticsearch.yml /elasticsearch/config/elasticsearch.yml

