#
# Copyright (C) ${year} Urchinly <wabi@urchinly.uk>
#

info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

server:
  port: 8081

spring:
  main:
    banner_mode: "off"
  jmx:
    enabled: false
  data:
    rest:
      default-page-size: 20
      max-page-size: 100

multipart:
  maxFileSize: 100MB
  maxRequestSize: 100MB
  file-size-threshold: 1MB

endpoints:
  health:
    sensitive: false
  restart:
    enabled: false
  shutdown:
    enabled: false
    
app:
  share:
    path: ${WABI_SHARE:./target/app-share}
