#
# Wabi-Sabi DAM solution
# Open source Digital Asset Management platform of great simplicity and beauty.
# Copyright (C) 2016 Urchinly <wabi-sabi@urchinly.uk>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

server:
  port: 8081

spring:
  main:
    banner_mode: "off"
  jmx:
    enabled: false
  data:
    rest:
      default-page-size: 20
      max-page-size: 100

multipart:
  maxFileSize: 100MB
  maxRequestSize: 100MB
  file-size-threshold: 1MB

endpoints:
  health:
    sensitive: false
  restart:
    enabled: false
  shutdown:
    enabled: false
    
app:
  share:
    path: ${WABI_SHARE:./target/app-share}
